[package]
name = "voidframe-mm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = { version = "0.9", default-features = false, features = ["mutex", "spin_mutex"] }

[profile.release]
panic = "abort"
lto = true
codegen-units = 1