[package]
name = "rust_core"
version = "0.1.0"
edition = "2021"

[dependencies]
linked_list_allocator = "0.10.5"

[lib]
name = "rust_core"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
