# ============================================================================
# Build Configuration
# ============================================================================
option(EXCLUDE_EXTRA_OBJECTS "Exclude extra objects from the build" OFF)
option(AUTOMATIC_POST "Run POST automatically on boot" OFF)
option(DEBUG_SYMBOLS "Enable debug symbols" ON)
option(STACK_PROTECTION "Enable stack protection" ON)
option(SILENT_BUILD "Enable silent build (suppress warnings)" OFF)

option(VF_CONFIG_ENABLE_VMWARE_SVGA_II "Enable VMware SVGA II support" OFF)
option(VF_CONFIG_ENABLE_CERBERUS_VFS_LOGGING "Enable Cerberus VFS logging" OFF)
option(VF_CONFIG_CERBERUS_THREAT_REPORTING "Enable Cerberus threat reporting" OFF)
option(VF_CONFIG_PANIC_OVERRIDE "Enable panic override" OFF)
option(VF_CONFIG_LOAD_MB_MODULES "Enable multiboot module loading" OFF)

option(VF_CONFIG_ENABLE_XHCI "Enable XHCI support" ON)
option(VF_CONFIG_ENABLE_VIRTIO "Enable VirtIO support" ON)
option(VF_CONFIG_ENABLE_ISA "Enable ISA support" ON)
option(VF_CONFIG_ENABLE_LPT "Enable LPT support" ON)
option(VF_CONFIG_ENABLE_PCI "Enable PCI support" ON)
option(VF_CONFIG_ENABLE_PS2 "Enable PS/2 support" ON)
option(VF_CONFIG_ENABLE_IDE "Enable IDE support" ON)
option(VF_CONFIG_ENABLE_VFCOMPOSITOR "Enable VFCompositor support" ON)
option(VF_CONFIG_ENABLE_AHCI "Enable AHCI support" ON)
option(VF_CONFIG_ENABLE_NVME "Enable NVMe support" ON)
option(VF_CONFIG_ENABLE_GENERIC_SOUND "Enable Generic Sound support" ON)
option(VF_CONFIG_RTC_CENTURY "Enable RTC Century support" ON)
option(VF_CONFIG_ENFORCE_MEMORY_PROTECTION "Enforce memory protection" ON)
option(VF_CONFIG_VM_HOST "Enable VM host optimizations" ON)
option(VF_CONFIG_SNOOZE_ON_BOOT "Enable snooze on boot" ON)
option(VF_CONFIG_USE_VFSHELL "Use VFShell as the default shell" ON)
option(VF_CONFIG_USE_DYNAMOX "Use Dynamox" ON)
option(VF_CONFIG_USE_ASTRA "Use Astra" ON)
option(VF_CONFIG_USE_CERBERUS "Use Cerberus" ON)
option(VF_CONFIG_CERBERUS_STACK_PROTECTION "Enable Cerberus stack protection" ON)
option(VF_CONFIG_INTEL "Enable Intel-specific optimizations" ON)
option(VF_CONFIG_ENABLE_OPIC "Enable OPIC support" ON)
option(VF_CONFIG_VESA_FB "Enable VESA framebuffer support" ON)
option(VF_CONFIG_MEMCPY_NT "Enable non-temporal memcpy optimizations" ON)
