# .github/workflows/main.yml
name: VoidFrame kernel build

on:
  pull_request:
    branches: [ main, dev ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            meson \
            nasm \
            xorriso \
            grub-pc-bin \
            grub-common \
            qemu-system-x86 \
            mtools \
            lld \
            llvm-objdump \

      - name: Compile & Link
        run: |
            meson setup build -Dexclude_extra_objects=true -Dautomatic_post=true
            ninja -C build

      - name: Artifact Analysis
        run: |
          timeout 30s ninja -C build runmin || true
          
          grep -q "1KCSWF23Z456789" build/bootstrap.log
          ! grep -i "panic\|fault\|crash\|oops\|error\|failed" build/serial.log
          
          ls -la build/voidframe.krnl
          test -s build/voidframe.krnl
          
          # Check if ISO was created
          ls -la build/VoidFrame.iso
          test -s build/VoidFrame.iso
          
          file build/voidframe.krnl | grep -q "ELF.*executable"
    
          # Verify kernel size is reasonable (not empty, not huge)
          KERNEL_SIZE=$(stat -c%s build/voidframe.krnl)
          test $KERNEL_SIZE -gt 100000    # > 100KB
          test $KERNEL_SIZE -lt 10000000  # < 10MB
          
          # Check ISO bootability
          file build/VoidFrame.iso | grep -q "ISO.*bootable"

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: voidframe-build-${{ github.sha }}
          path: |
            build/voidframe.krnl
            build/VoidFrame.iso
          retention-days: 30