# .github/workflows/main.yml
name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main, dev ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            nasm \
            xorriso \
            grub-pc-bin \
            grub-common \
            qemu-system-x86 \
            mtools \
            lld \
            llvm \
            cmake
          pip3 install meson>=1.4.0

      - name: Compile & Link (CMake & Meson)
        run: |
            meson setup meson-build -Dexclude_extra_objects=true -Dautomatic_post=true
            ninja -C meson-build
            mkdir cmake-build
            cd cmake-build
            cmake .. -G Ninja
            cd ..
            ninja -C cmake-build
            rm -rf cmake-build

      - name: Artifact Analysis
        run: |
          timeout 30s ninja -C meson-build runmin || true
          
          grep -q "1KCSWF23Z456789" meson-build/bootstrap.log
          ! grep -i "panic\|fault\|crash\|oops\|error\|failed" meson-build/serial.log
          
          ls -la meson-build/voidframe.krnl
          test -s meson-build/voidframe.krnl
          
          # Check if ISO was created
          ls -la meson-build/VoidFrame.iso
          test -s meson-build/VoidFrame.iso
          
          file meson-build/voidframe.krnl | grep -q "ELF.*executable"
    
          # Verify kernel size is reasonable (not empty, not huge)
          KERNEL_SIZE=$(stat -c%s meson-build/voidframe.krnl)
          test $KERNEL_SIZE -gt 100000    # > 100KB
          test $KERNEL_SIZE -lt 10000000  # < 10MB
          
          # Check ISO bootability
          file meson-build/VoidFrame.iso | grep -q "ISO.*bootable"

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: voidframe-build-${{ github.sha }}
          path: |
            meson-build/voidframe.krnl
            meson-build/VoidFrame.iso
          retention-days: 30